package:
  name: libastra
  version: '1.9.0.dev11'

source:
  git_url: https://github.com/astra-toolbox/astra-toolbox.git
  git_tag: master

build:
  number: 0
  script_env:
    - CC # [linux]
    - CXX # [linux]

requirements:
  build:
    - {{compiler('c')}} # [win]
    - boost # [osx]
    - automake # [osx]
    - autoconf # [osx]
    - libtool # [osx]
    - cudatoolkit {{ cudatoolkit }} # [linux]

  run:
    - cudatoolkit {{ cudatoolkit }} # [linux]

about:
  home: http://www.astra-toolbox.com
  license: GPLv3
  summary: 'The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.'
